local function AddPlayerModel( name, model )

    list.Set( "PlayerOptionsModel", name, model )
    player_manager.AddValidModel( name, model )
	
end

AddPlayerModel( "DOD German Male02", "models/dodhacks/germanmale02.mdl" )
AddPlayerModel( "DOD German Male02 Afrika", "models/dodhacks/germanmale02ak.mdl" )
AddPlayerModel( "DOD German Male04", "models/dodhacks/germanmale04.mdl" )
AddPlayerModel( "DOD German Male04 Afrika", "models/dodhacks/germanmale04ak.mdl" )
AddPlayerModel( "DOD German Male06", "models/dodhacks/germanmale06.mdl" )
AddPlayerModel( "DOD German Male06 Afrika", "models/dodhacks/germanmale06ak.mdl" )
AddPlayerModel( "DOD German Male07", "models/dodhacks/germanmale07.mdl" )
AddPlayerModel( "DOD German Male07 Afrika", "models/dodhacks/germanmale07ak.mdl" )
AddPlayerModel( "DOD German Male08", "models/dodhacks/germanmale08.mdl" )
AddPlayerModel( "DOD German Male08 Afrika", "models/dodhacks/germanmale08ak.mdl" )
AddPlayerModel( "DOD German Male09", "models/dodhacks/germanmale09.mdl" )
AddPlayerModel( "DOD German Male09 Afrika", "models/dodhacks/germanmale09ak.mdl" )
AddPlayerModel( "DOD US Male01", "models/dodhacks/usmale01.mdl" )
AddPlayerModel( "DOD US Male01 Marine", "models/dodhacks/usmale01pa.mdl" )
AddPlayerModel( "DOD US Male02", "models/dodhacks/usmale02.mdl" )
AddPlayerModel( "DOD US Male02 Marine", "models/dodhacks/usmale02pa.mdl" )
AddPlayerModel( "DOD US Male03", "models/dodhacks/usmale03.mdl" )
AddPlayerModel( "DOD US Male03 Marine", "models/dodhacks/usmale03pa.mdl" )
AddPlayerModel( "DOD US Male04", "models/dodhacks/usmale04.mdl" )
AddPlayerModel( "DOD US Male04 Marine", "models/dodhacks/usmale04pa.mdl" )
AddPlayerModel( "DOD US Male06", "models/dodhacks/usmale06.mdl" )
AddPlayerModel( "DOD US Male06 Marine", "models/dodhacks/usmale06pa.mdl" )
AddPlayerModel( "DOD US Male07", "models/dodhacks/usmale07.mdl" )
AddPlayerModel( "DOD US Male07 Marine", "models/dodhacks/usmale07pa.mdl" )
AddPlayerModel( "DOD US Male08", "models/dodhacks/usmale08.mdl" )
AddPlayerModel( "DOD US Male08 Marine", "models/dodhacks/usmale08pa.mdl" )
AddPlayerModel( "DOD US Male09", "models/dodhacks/usmale09.mdl" )
AddPlayerModel( "DOD US Male09 Marine", "models/dodhacks/usmale09pa.mdl" )