player_manager.AddValidModel( "SenMob Greaser1", "models/sentry/sentryoldmob/greaser/sentrygreasemale2pm.mdl" )
player_manager.AddValidModel( "SenMob Greaser2", "models/sentry/sentryoldmob/greaser/sentrygreasemale4pm.mdl" )
player_manager.AddValidModel( "SenMob Greaser3", "models/sentry/sentryoldmob/greaser/sentrygreasemale7pm.mdl" )
player_manager.AddValidModel( "SenMob Greaser4", "models/sentry/sentryoldmob/greaser/sentrygreasemale9pm.mdl" )
player_manager.AddValidModel( "SenMob Irish1", "models/sentry/sentryoldmob/irish/sentryirishmale2pm.mdl" )
player_manager.AddValidModel( "SenMob Irish2", "models/sentry/sentryoldmob/irish/sentryirishmale4pm.mdl" )
player_manager.AddValidModel( "SenMob Irish3", "models/sentry/sentryoldmob/irish/sentryirishmale6pm.mdl" )
player_manager.AddValidModel( "SenMob Irish4", "models/sentry/sentryoldmob/irish/sentryirishmale7pm.mdl" )
player_manager.AddValidModel( "SenMob Irish5", "models/sentry/sentryoldmob/irish/sentryirishmale8pm.mdl" )
player_manager.AddValidModel( "SenMob Irish6", "models/sentry/sentryoldmob/irish/sentryirishmale9pm.mdl" )
player_manager.AddValidModel( "SenMob Mafia1", "models/sentry/sentryoldmob/mafia/sentrymobmale2pm.mdl" )
player_manager.AddValidModel( "SenMob Mafia2", "models/sentry/sentryoldmob/mafia/sentrymobmale4pm.mdl" )
player_manager.AddValidModel( "SenMob Mafia3", "models/sentry/sentryoldmob/mafia/sentrymobmale6pm.mdl" )
player_manager.AddValidModel( "SenMob Mafia4", "models/sentry/sentryoldmob/mafia/sentrymobmale7pm.mdl" )
player_manager.AddValidModel( "SenMob Mafia5", "models/sentry/sentryoldmob/mafia/sentrymobmale8pm.mdl" )
player_manager.AddValidModel( "SenMob Mafia6", "models/sentry/sentryoldmob/mafia/sentrymobmale9pm.mdl" )
player_manager.AddValidModel( "SenMob Chinese", "models/sentry/sentryoldmob/chinese/oldchinesegoonpm.mdl" )
player_manager.AddValidModel( "SenMob Bouncer1", "models/sentry/sentryoldmob/oldgoons/sentryarmbmale2pm.mdl" )
player_manager.AddValidModel( "SenMob Bouncer2", "models/sentry/sentryoldmob/oldgoons/sentryarmbmale8pm.mdl" )
player_manager.AddValidModel( "SenMob Bouncer3", "models/sentry/sentryoldmob/oldgoons/sentryarmbmale6pm.mdl" )
player_manager.AddValidModel( "SenMob Suit1", "models/sentry/sentryoldmob/oldgoons/sentrybusi1male2pm.mdl" )
player_manager.AddValidModel( "SenMob Suit2", "models/sentry/sentryoldmob/oldgoons/sentrybusi1male4pm.mdl" )
player_manager.AddValidModel( "SenMob Suit3", "models/sentry/sentryoldmob/oldgoons/sentrybusi1male6pm.mdl" )
player_manager.AddValidModel( "SenMob Suit4", "models/sentry/sentryoldmob/oldgoons/sentrybusi1male7pm.mdl" )
player_manager.AddValidModel( "SenMob Suit5", "models/sentry/sentryoldmob/oldgoons/sentrybusi1male8pm.mdl" )
player_manager.AddValidModel( "SenMob Suit6", "models/sentry/sentryoldmob/oldgoons/sentrybusi1male9pm.mdl" )
player_manager.AddValidModel( "SenMob British1", "models/sentry/sentryoldmob/britgoons/sentrybritmale4pm.mdl" )
player_manager.AddValidModel( "SenMob British2", "models/sentry/sentryoldmob/britgoons/sentrybritmale6pm.mdl" )
player_manager.AddValidModel( "SenMob British3", "models/sentry/sentryoldmob/britgoons/sentrybritmale8pm.mdl" )
player_manager.AddValidModel( "SenMob British4", "models/sentry/sentryoldmob/britgoons/sentrybritmale9pm.mdl" )
player_manager.AddValidModel( "SenMob Sicilian1", "models/sentry/sentryoldmob/slygoons/sentryslymale6pm.mdl" )
player_manager.AddValidModel( "SenMob Sicilian2", "models/sentry/sentryoldmob/slygoons/sentryslymale7pm.mdl" )
player_manager.AddValidModel( "SenMob Sicilian3", "models/sentry/sentryoldmob/slygoons/sentryslymale8pm.mdl" )
player_manager.AddValidModel( "SenMob Sicilian4", "models/sentry/sentryoldmob/slygoons/sentryslymale9pm.mdl" )

local nextName
local tbNPCs = {}

local function AddNPC(category, name, class, model, keyvalues, weapons, spawnflags)
		list.Set("NPC",name,{Name = name,Class = class,Model = model,Category = category,KeyValues = keyvalues,Weapons = weapons, SpawnFlags = spawnflags})
		tbNPCs[name] = model
end

AddNPC("GTA V", "Past Triad Member", "npc_citizen", "models/sentry/sentryoldmob/chinese/oldchinesegoong.mdl", {citizentype = CT_UNIQUE, SquadName = "rebels"}, {"weapon_pistol","weapon_smg1"})
AddNPC("GTA V", "Past Triad Member (Hostile)", "npc_combine_s", "models/sentry/sentryoldmob/chinese/oldchinesegoonh.mdl", {citizentype = CT_UNIQUE, SquadName = "us"}, {"weapon_pistol","weapon_smg1"})
